### ISSUE TITLE
Build with boost-1.85 failed

### ISSUE THREAD

**Issue by Pro-pra** [fifengine/fifengine#1085]
```
/builddir/build/BUILD/fifengine-0.4.2/engine/core/loaders/native/map/atlasloader.cpp:315:62: error: 'extension' is not a member of 'bfs'
  315 |                                 std::string extension = bfs::extension(*atlasSource);
 ```

boost developer recommendeted this issue:
```
Replace extension(p) with p.extension().string()
```

I`m not programmer and no pull request from me, please fix build with boost-1.85

**Comment by 0-wiz-0** [comment]
I saw this too and tried both `(*foo).extension().string()` and `foo->extension().string()` but neither worked because strings don't provide an `extension()` - so either I misunderstood upstream or they were wrong.

**Comment by stoecker** [comment]
Following fixes build together with -DCMAKE_CXX_FLAGS='-DUSE_BOOST_FILESYSTEM_V3'

Untested whether everything works with this change. Please can somebody check and report?
```
diff -ur fifengine-0.4.2/engine/core/gui/fifechan/fifechanmanager.cpp fifengine-0.4.2_fix/engine/core/gui/fifechan/fifechanmanager.cpp
--- fifengine-0.4.2/engine/core/gui/fifechan/fifechanmanager.cpp	2019-01-11 18:24:38.000000000 +0100
+++ fifengine-0.4.2_fix/engine/core/gui/fifechan/fifechanmanager.cpp	2024-05-16 14:55:36.964378748 +0200
@@ -249,7 +249,13 @@
 
 		IFont* font = NULL;
 		GuiFont* guifont = NULL;
+                #if defined(USE_BOOST_FILESYSTEM_V3)
+                bfs::path p = fontpath;
+                std::string s = p.extension().string();
+                if( s == ".ttf" || s == ".ttc" ) {
+                #else
 		if( bfs::extension(fontpath) == ".ttf" || bfs::extension(fontpath) == ".ttc" ) {
+		#endif
 			font = new TrueTypeFont(fontpath, fontsize);
 		} else {
 			font = new SubImageFont(fontpath, fontglyphs);
diff -ur fifengine-0.4.2/engine/core/loaders/native/map/atlasloader.cpp fifengine-0.4.2_fix/engine/core/loaders/native/map/atlasloader.cpp
--- fifengine-0.4.2/engine/core/loaders/native/map/atlasloader.cpp	2019-01-11 18:24:38.000000000 +0100
+++ fifengine-0.4.2_fix/engine/core/loaders/native/map/atlasloader.cpp	2024-05-16 14:59:14.130949570 +0200
@@ -312,7 +312,12 @@
 				atlasElem->QueryValueAttribute("subimage_width", &subimageWidth);
 				atlasElem->QueryValueAttribute("subimage_height", &subimageHeight);
 				// file extension of the atlas is also used as subimage extension
-				std::string extension = bfs::extension(*atlasSource);
+                                #if defined(USE_BOOST_FILESYSTEM_V3)
+                                    bfs::path p = *atlasSource;
+                                    std::string extension = p.extension().string();
+                                #else
+                                    std::string extension = bfs::extension(*atlasSource);
+                                #endif
 				// we need an atlas id
 				if (!atlasId) {
 					atlasId = atlasSource;
diff -ur fifengine-0.4.2/engine/core/loaders/native/map/maploader.cpp fifengine-0.4.2_fix/engine/core/loaders/native/map/maploader.cpp
--- fifengine-0.4.2/engine/core/loaders/native/map/maploader.cpp	2019-01-11 18:24:38.000000000 +0100
+++ fifengine-0.4.2_fix/engine/core/loaders/native/map/maploader.cpp	2024-05-16 14:59:24.034430591 +0200
@@ -838,7 +838,13 @@
 			for (iter = files.begin(); iter != files.end(); ++iter) {
 				// TODO - vtchill - may need a way to allow clients to load things other
 				// than .xml and .zip files
-				std::string ext = bfs::extension(*iter);
+				#if defined(USE_BOOST_FILESYSTEM_V3)
+				    bfs::path p = *iter;
+                                    std::string ext = p.extension().string();
+                                #else
+                                    std::string ext = bfs::extension(*iter)
+                                #endif
+
 				if (ext == ".xml" || ext == ".zip") {
 					loadImportFile(*iter, importDirectoryString);
 				}
diff -ur fifengine-0.4.2/engine/core/loaders/native/map/objectloader.cpp fifengine-0.4.2_fix/engine/core/loaders/native/map/objectloader.cpp
--- fifengine-0.4.2/engine/core/loaders/native/map/objectloader.cpp	2019-01-11 18:24:38.000000000 +0100
+++ fifengine-0.4.2_fix/engine/core/loaders/native/map/objectloader.cpp	2024-05-16 14:59:19.167691348 +0200
@@ -702,7 +702,13 @@
 			for (iter = files.begin(); iter != files.end(); ++iter) {
 				// TODO - vtchill - may need a way to allow clients to load things other
 				// than .xml and .zip files
-				std::string ext = bfs::extension(*iter);
+                                #if defined(USE_BOOST_FILESYSTEM_V3)
+                                    bfs::path p = *iter;
+                                    std::string ext = p.extension().string();
+                                #else
+                                    std::string ext = bfs::extension(*iter)
+                                #endif
+				
 				if (ext == ".xml" || ext == ".zip") {
 					loadImportFile(*iter, importDirectoryString);
 				}
```

**Comment by Pro-pra** [comment]
thank you, compiled fine!

**Comment by stoecker** [comment]
Why is this completed? Neither was this patch nor something similar applied.

**Comment by Pro-pra** [comment]
i use this patch in my distrib, build fine.

**Comment by stoecker** [comment]
What does that help? If its not applied to the software it's not fixed. Applying a patch is only a workaround.

**Comment by LinuxDonald** [comment]
@jakoch could you please take an look on this?

**Comment by AngryPenguinPL** [comment]
It need another patch with boost 1.86

Now failing with:
```

 /builddir/build/BUILD/fifengine-0.4.2-build/fifengine-0.4.2/engine/core/loaders/native/map/objectloader.cpp:709:55: error: no member named 'extension' in namespace 'boost::filesystem'; did you mean 'GetExtension'?
DEBUG util.py:463:    709 |                                     std::string ext = bfs::extension(*iter)
DEBUG util.py:463:        |                                                       ^~~~~~~~~~~~~~
DEBUG util.py:463:        |                                                       GetExtension
DEBUG util.py:463:  /builddir/build/BUILD/fifengine-0.4.2-build/fifengine-0.4.2/engine/core/vfs/fife_boost_filesystem.h:101:17: note: 'GetExtension' declared here
DEBUG util.py:463:    101 |     std::string GetExtension(const std::string& path);
DEBUG util.py:463:        |                 ^
DEBUG util.py:463:  /builddir/build/BUILD/fifengine-0.4.2-build/fifengine-0.4.2/engine/core/loaders/native/map/objectloader.cpp:709:76: error: expected ';' at end of declaration
DEBUG util.py:463:    709 |                                     std::string ext = bfs::extension(*iter)
DEBUG util.py:463:        |                                                                            ^
DEBUG util.py:463:        |                 
```                                                           ;
