### ISSUE TITLE
How to package fifengine correctly?

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifengine#907]
I need some guidance on what to package for which target.

**Appveyor  - MSVC**
The current release for MSVC looks like this:
https://ci.appveyor.com/api/buildjobs/1jr93aqlgoexunv6/artifacts/fifengine-VC.zip
- Is the name correct? Or should this be `libfife-VC.zip`
- Should `fifechan` be included? 
- To support a C++ upstream project (e.g. the [cpp-tutorial1](https://github.com/fifengine/cpp-tutorials/blob/master/src/tutorial_1/CMakeLists.txt)), we need to add the header includes and somehow generate a shared binary file `fifengine.dll`, right? Shared lib is not in the CMakeList.txt, yet, right?
- I guess the C++ header includes are not needed for a Python client, right?
  - https://github.com/fifengine/fifengine/blob/master/CMakeLists.txt#L496-L503
  - Should we release separately for Python and C++ clients?

**Comment by prock-fife** [comment]
> Is the name correct? Or should this be libfife-VC.zip
I would prefer libfife-vcXX.zip where XX is the version of VC it was compiled with.
> Should fifechan be included?
I'm not sure... worth some discussion.
> To support a C++ upstream project, we need to add the header includes and somehow generate a shared binary file fifengine.dll, right?
There are some underlying issues with DLLs at the moment so it's not supported.  Right now we only support linking fife statically.
> Are the C++ header includes also needed for a Python client?
No
> Should we release separately for Python and C++ clients?
Yes but lets discuss.

On Windows up until this point we have only been releasing the python library and supporting binaries along with the demos and editor (all in one installer).  We need to decide exactly how we want to release everything from now on.  

From my point of view we may have 2 types of people who will download something like this.  1) python game developers who want to develop a game and generally have no intention of modifying the engine.  2) C++ game developers who do not want to use the python bindings and want to statically link FIFE in their project.  My preference would be to have 2 packages.  1 that includes everything someone needs (minus python itself) to use FIFE.  See this file for how to create the python module for and FIFE installer: https://github.com/fifengine/fifengine/blob/master/build/win32/installer/README.txt  It's a bit short but it has all the basic steps in there. 2, this package will include all the binaries and headers required for C++ game developers to statically link fife to their game and this is where the dev kit comes in.  The dev kit should include all dependency binaries required for projects to statically link fife to their games.  Really the dev kit serves two purposes..  the first is to allow FIFE developers to easily set up a development environment to work on FIFE itself.  and the second is to allow game developers to easily link to FIFE.

On Linux (it's probably worth talking about Linux a bit) packagers have been creating a libfife package that you can install with the package manager.  It does not normally (to my knowledge) include the demos or anything else for that matter.  This is generally done to support the install of Unknown Horizons.   I would like to see the demos and editor become packages but that's really up to the package maintainers as we don't have the people to do something like that.

**Comment by jakoch** [comment]
Thank you :)

> I would prefer libfife-vcXX.zip where XX is the version of VC it was compiled with

Ok, no problem. Do you want the same change for fifechan?

What about `-win32` indication?

> There are some underlying issues with DLLs at the moment so it's not supported. Right now we only support linking fife statically.

Is there a ticket for these underlying issues?

The C++ package will miss the binaries then (until the issues are resolved).
I will prepare this, but it will only include the lib and the header includes for now.

> My preference would be to have 2 packages.

Ok, that makes perfect sense. Let's do this.

> On Linux packagers have been creating a libfife package

Right, i've seen `python-fife` over at the [unknown-horizons travis.yml](https://github.com/unknown-horizons/unknown-horizons/blob/master/.travis.yml#L8).

> demos and editor become packages but that's really up to the package maintainers as we don't have the people to do something like that

Ok.

But the same issue pops up for the installers, right?
Now that the demos are moved, i would need to fetch them again, right?
https://github.com/fifengine/fifengine/blob/master/build/win32/installer/fife.iss#L61

**Comment by vtchill** [comment]
I agree with everything @prock-fife said in answering the questions. I just wanted to add to the discussion about the DLL issues a bit. There is a potential for confusion when talking about creating a project with fife using c++. 

I see 2 things that are worth discussion:
1) Your project need to load the fife library (either static or dynamic)
2) fife needs to be able to load any of its dependencies (either they are all baked into the library  or it knows how to find and load them through other static or dynamic libraries).

For #1 the only option is a static library (.lib in the windows world). The reason behind this is fairly fundamental and it has to do with how you have to structure your code to be exportable in a dynamic library. You have to be very careful about what gets passed across DLL boundaries to avoid issues with memory management and ABI compatibility in c++. Most DLLs take the approach of a c-style exported interface to avoid the issues mentioned. For fife this is a huge rework and would require lots of thought about what our API should look like to outside clients.

For #2 This is really dependent on how we build the fife dependencies and how fife links to these. This should not really be a huge issue for people creating a project using fife provided that the fife installer puts any needed libraries in known locations and provides the correct headers.

**Comment by jakoch** [comment]
Thank you for explaining the `.dll` situation. 

Please let me summarize the artifacts produced by Appveyor for MSVC:
- `fifengine-cpp-*-VC14.zip` ships `lib` and `includes`
- `fifengine-python-*-VC14.zip` ships `lib`,`pyd` and the `python stuff`
   - `C:\Python35\Lib\site-packages\fife`
- `fife-x.y.z.exe` (python module installer)
   - build with `python setup.py bdist_wininst`
- `fifengine-dependencies-*.zip`

Anything missing?

----

- When building the python module installer exe i need to pass the version number in by using a parameter, right? Normally hardcoded: https://github.com/fifengine/fifengine/blob/master/setup.py#L36
  - i will try `python setup.py bdist_wininst --target-version="x.y.z"`
- I could probably use `python setup.py bdist_dump --format=zip`  to create the zip, right? Basically, what i'm trying to do now manually.

**Comment by jakoch** [comment]
The readme states that i should copy DLLs, which i don't have, https://github.com/fifengine/fifengine/blob/master/build/win32/installer/README.txt#L5
This is the result of the build: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-52d6e66#L4153
How does this fit together?

**Comment by jakoch** [comment]
**PythonInstallerArtifact**
The command doesn't do much. The [Python manual says](https://docs.python.org/3.6/distutils/builtdist.html#creating-windows-installers) that the files normally go into a `dist` folder, but it's not created and nothing is build. Any hints? 

https://ci.appveyor.com/project/jakoch/fifengine/build/dev-03b2a03#L4198

**Dependencies Artifact**
The dependencies are now available as a zip:
https://ci.appveyor.com/project/jakoch/fifengine/build/dev-05c0503/artifacts

**Comment by Niektory** [comment]
I think The DLLs to be copied = the .pyd files + dependencies.

**Comment by jakoch** [comment]
I'm not sure.. 

but, finally ... 🚀
**Build success**
- Uploading artifact `dist\libfife-python-0.4.0.win32.exe` (1.9 MB)...OK
- Uploading artifact `libfife-dependencies-dev-9ba4568-VC14.zip` (22 MB)...OK

https://ci.appveyor.com/project/jakoch/fifengine/build/dev-9ba4568/artifacts

Please give me a feedback, if these artifacts are ok or if they need further work.

**Comment by LinuxDonald** [comment]
@vtchill @prock-fife could it get merged?

**Comment by prock-fife** [comment]
> I copied the pyd and lib. But i'm also not sure, if i need to copy all dependency dlls there.

The python installer should have all required libraries in it so someone can start using the python library right after installing it.  I have no way to test it at the moment.

Is the dependencies zip intended to be for exactly?

**Comment by jakoch** [comment]
> The python installer should have all required libraries in it so someone can start using the python library right after installing it.

Ok, i adjust the build script to copy all dlls into the folder.

>  I have no way to test it at the moment.

The new dev-kit is missing, isn't it?

> Is the dependencies zip intended to be for exactly?

The dependencies.zip will be part of the fife-sdk for VC14.
The other part are the build-tools: swig, python, cmake.
All packaged in one installer. That means the dev gets a complete SDK, where only Visual Studio is missing to start working. Does that make sense to you?

**Comment by Niektory** [comment]
The `libfife-python-0.4.0.win32.exe` installer doesn't work for me. The error message says "Python version -32 required, which was not found in the registry." Weird. Perhaps specyfying a target version would help:
`python setup.py bdist_wininst --target-version=2.7`
Or maybe it's something on my end, but other installers seem to work...

Another issue: `fife.py` and `fifechan.py` seem to not be included. Are they even built? I don't really know how the SWIG/CMake magic works. Wild guess: Add a `-python` option here:
https://github.com/jakoch/fifengine/blob/master/CMakeLists.txt#L545

**Comment by jakoch** [comment]
Thanks for testing and providing feedback. 
Ok, let's try your suggestions..

**Comment by prock-fife** [comment]
> no .dll and no .py :(

Do we need the .py?  It's been a while since I looked at it but I seem to recall not needing those files as python will know what to do when you import fife.

@Niektory what version of python do you have installed?  64bit or 32bit?

**Comment by Niektory** [comment]
32-bit installer from python.org:
`Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32`
The OS is Windows 7 64-bit.

**Comment by jakoch** [comment]
Not sure what the `-python` flag does to Swig, but it broke the build.
Then i had some trouble with the artifact filename, because it's automatically versionized.
Here we go again with a new python installer for 2.7:
https://ci.appveyor.com/api/buildjobs/fcriq2sv10rqbalg/artifacts/libfife-0.4.0.win32-py2.7.exe

**Comment by Niektory** [comment]
The new installer works. However, the installed fife module is empty, probably the result of the missing .py files.
```
>>> from fife import fife
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name fife
>>> import fife
>>> fife
<module 'fife' from 'C:\Python27\lib\site-packages\fife\__init__.pyc'
>>>> dir(fife)
['__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
```

**Comment by jakoch** [comment]
Well, at least the installer is now working :)

I opened the `.pyd` in DependencyWalker:
![dependencywalker-fife pyd](https://cloud.githubusercontent.com/assets/85608/18456041/39903272-794e-11e6-9fae-808820d9742c.png)

Some dependencies are missing: fifechan and python.

The binary extension expects a `Python34.dll`.
The `.pyd` is build with Python 3.5.2-32bit, shouldn't this be `Python35.dll` dependency then?https://ci.appveyor.com/project/jakoch/fifengine/build/dev-f5e3c5d#L19

**Comment by Niektory** [comment]
Could you add `dir C:\projects\build /s` at the end of the build?

**Comment by jakoch** [comment]
Added: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-42779ea#L4427

**Comment by jakoch** [comment]
Switched to Python2.7 on Appveyor using `-DPYTHON_INCLUDE_DIR="C:/Python27/include"` and `-DPYTHON_LIBRARY="C:/Python27/libs/python27.lib"`. Finally PythonLibs are correctly detected.
The include in now `Python27.dll`.
And the file has to be on the env PATH to be found.

Latest build: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-cd41d3a/artifacts

![dw-fifepyd](https://cloud.githubusercontent.com/assets/85608/18468783/c2de47f6-79a5-11e6-83f6-c38932dd8571.png)

**Comment by Niektory** [comment]
We still need `fife.py` nad `fifechan.py`. They were there all along:
https://ci.appveyor.com/project/jakoch/fifengine/build/dev-42779ea#L4437
https://ci.appveyor.com/project/jakoch/fifengine/build/dev-42779ea#L4439

**Comment by jakoch** [comment]
Found out that the `.py` file isn't amongst the copied files by `setup.py`, see
https://github.com/fifengine/fifengine/blob/master/setup.py#L30
Fix incoming.

**Comment by jakoch** [comment]
Ok, i tried to include the `.py`: https://github.com/jakoch/fifengine/commit/c8b677f5a7eb76ee6130bc49860cbc6d5a5d3b06, bBut it that didn't work out: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-c8b677f#L4113

**Comment by Niektory** [comment]
I don't think you need to edit setup.py, just copy the files to engine\python\fife before running it.

**Comment by jakoch** [comment]
I think setup.py packages the wrong folder...

The files are already copied by CMakeLists, see
https://github.com/jakoch/fifengine/blob/master/CMakeLists.txt#L588
https://github.com/jakoch/fifengine/blob/master/CMakeLists.txt#L594

`install(FILES       ${PROJECT_BINARY_DIR}/fife.py                       DESTINATION ${PYTHON_SITE_PACKAGES}/fife)`

`${PYTHON_SITE_PACKAGES}/fife` resolves to 'C:\Python27\Lib\site-packages/fife'.
That's the Python Install dir.

From my point of view the `setup.py` should package the stuff in `C:\Python27\Lib\site-packages\fife` and not the stuff in `C:\projects\fifengine\engine\python\fife`.

**Comment by jakoch** [comment]
Ok, the files are now copied:
https://ci.appveyor.com/api/buildjobs/nygkimxnb6u5mj7f/artifacts/libfife-0.4.0.win32-py2.7.exe

**Comment by Niektory** [comment]
OK, the module can be imported normally now. I've tried to run the demos from https://github.com/fifengine/fifengine-demos.

shooter, rpg and pychan demos run and show the interface, but clicking a button results in the following error:
`_[SDLException]_ , SDL reported something bad :: Fatal Error when loading image into a SDL_Surface: Failed loading libpng16-16.dll: Nie można odnaleźć określonego modułu.` (translation: cannot find the specified module)

rio_de_hola doesn't start:
```
Traceback (most recent call last):
  File "./run.py", line 174, in <module>
    main()
  File "./run.py", line 147, in main
    app = IslandDemo()
  File "./run.py", line 122, in __init__
    super(IslandDemo,self).__init__(TDS)
  File "C:\Python27\lib\site-packages\fife\extensions\pychan\pychanbasicapplication.py", line 68, in __init__
    super(PychanApplicationBase, self).__init__(setting)
  File "C:\Python27\lib\site-packages\fife\extensions\basicapplication.py", line 77, in __init__
    self.initLogging()
  File "C:\Python27\lib\site-packages\fife\extensions\basicapplication.py", line 185, in initLogging
    self._setting.get("FIFE", "LogToFile", False))
  File "C:\Python27\lib\site-packages\fife\extensions\fifelog.py", line 42, in __init__
    self.lm.setLogToPrompt(promptlog)
  File "C:\Python27\lib\site-packages\fife\fife.py", line 14105, in setLogToPrompt
    return _fife.LogManager_setLogToPrompt(self, logtoprompt)
TypeError: in method 'LogManager_setLogToPrompt', argument 2 of type 'bool'
```

**Comment by jakoch** [comment]
Thanks for testing. I can confirm this issue with `libpng16-16.dll`.
Somehow the file isn't loaded, when it resides in the fife folder.

**Workaround**
copy the dll directly into the demo folders (next to `run.py`), then shooter and rpg will run

rio_de_hola: hmm, maybe it's out-of-sync with fife and needs an update

**Comment by jakoch** [comment]
Now that we have a working Python installer, let's focus on the C++ side of things.
I'm using the artifacts of this repository over at the cpp-tutorial, but it doesn't compile.
- https://ci.appveyor.com/project/jakoch/fifengine-cpp-tutorials/build/dev-e2da669/messages
- https://ci.appveyor.com/project/jakoch/fifengine-cpp-tutorials/build/dev-e2da669

Seems, i'm running into the issues mentions by @vtchill in https://github.com/fifengine/fifengine/issues/907#issuecomment-245945618

What do i have to change?

**Comment by vtchill** [comment]
It looks like during the link phase dlls are not found for SDL and its dependencies. I'm not sure how appveyor works but in general all the dynamlc libraries (dlls) will need to be in either the same path as fife.lib (and the c++ application .exe) or in some system path that is on the search path for dll loading. Usually the current path is the easiest to accomplish.

**Comment by vtchill** [comment]
I would not be surprised to see compile errors in the cpp-tutorials project since it probably does not match to the interface of the current version of fife, unless someone has updated it recently.

**Comment by prock-fife** [comment]
I believe someone had the CPP tutorials working a few months ago.  Seems just to be a linking issue.

**Comment by jakoch** [comment]
> It looks like during the link phase dlls are not found for SDL and its dependencies.

 👍  Thanks for the SDL pointer!

I checked the includes once more and noticed that `fifechan_sdl` and `fifechan_opengl` are not linked.
This was because `FindFifeChan.cmake` only detected `fifechan.lib` itself, but not the components !
Now, that i've added component support (`find_package(FifeChan COMPONENTS opengl sdl REQUIRED) `) the libs are found and the tutorial compiles successfully.

**Comment by vtchill** [comment]
great new @jakoch - thanks for all the awesome work!

**Comment by jakoch** [comment]
You're welcome.

> I would not be surprised to see compile errors in the cpp-tutorials project since it probably does not match to the interface of the current version of fife, unless someone has updated it recently.

![dw_tutorial1exe](https://cloud.githubusercontent.com/assets/85608/18729821/ab0fcea6-8053-11e6-9f09-2ca10b0dd951.png)

The `Tutorial1.exe` is build, dependencies are resolved, but it crashes.
Seems it needs an update...

**Comment by prock-fife** [comment]
I don't have the ability to run them at the moment.  Can you post the the back trace?

**Comment by prock-fife** [comment]
@Niektory I just downloaded the 32 bit version of Python 2.7.12 and installed in on Windows 10.  I then downloaded and installed the latest FIFE python module.  Now I get the following:

```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=== RESTART: C:\Users\prasek\Projects\FIFE\fifengine-demos\shooter\run.py ===

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fife\fife.py", line 21, in <module>
    _fife = swig_import_helper()
  File "C:\Python27\lib\site-packages\fife\fife.py", line 20, in swig_import_helper
    return importlib.import_module('_fife')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _fife
```

Here is some more information:

```
>>> import fife
>>> help(fife
     )
Help on package fife:

NAME
    fife - # -*- coding: utf-8 -*-

FILE
    c:\python27\lib\site-packages\fife\__init__.py

PACKAGE CONTENTS
    _fife
    _fifechan
    extensions (package)
    fife
    fifechan

DATA
    __all__ = ['fife']


>>>
``` 

Any hints?  This is a fresh install of Windows 10 as well.

**Comment by prock-fife** [comment]
This is the python FIFE module that I installed ->  https://ci.appveyor.com/api/buildjobs/rvwtnq9i0uhhclhm/artifacts/libfife-dev-018c9f2.win32-py2.7.exe

**Comment by jakoch** [comment]
This was the first build of a working installer
https://ci.appveyor.com/api/buildjobs/nygkimxnb6u5mj7f/artifacts/libfife-0.4.0.win32-py2.7.exe
Seems i broke something along the way...

**Comment by jakoch** [comment]
That means that the last working installer was build 16 days ago.
We need to find a breaking change related to package inclusion around that time.
That happens either in CMakeLists.txt or appveyor.yml.

Now we have:
```
PACKAGE CONTENTS
    _fife
    _fifechan
    extensions (package)
    fife                                            ... this is new?
    fifechan                                    ... this is new?
```

Before:
```
PACKAGE CONTENTS
    _fife
    _fifechan
    extensions (package)
```

**Comment by Niektory** [comment]
Yup this one works. :+1:

**Comment by jakoch** [comment]
Ok, now that we have again a working Py2.7 installer, we can tackle the next issue:
did someone test the Py3 installer?

**Comment by LinuxDonald** [comment]
Give an way that the python3 installer and maybe py2 installs python on the pc if it needed?

**Comment by LinuxDonald** [comment]
The py3 installer dont find my python 3.5.2

**Comment by jakoch** [comment]
> Give an way that the python3 installer and maybe py2 installs python on the pc if it needed?

The installation of the build-tools will be / is part of the fife-sdk installer.

**Comment by jakoch** [comment]
This is solved:
Status: 
- Except Linux packaging. 
- Except Mac packaging.
- We are consuming the artifacts of fifengine (libfife python for 2.7 and 3.x + dependencies) in the FifeSDK now. See https://github.com/fifengine/fife-windows-sdk
