### ISSUE TITLE
make fails due to "error: ‘Point’ is not a member of ‘fcn’"

### ISSUE THREAD

**Issue by krichter722** [fifengine/fifengine#1000]
After installing `fifechan` with `mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..` and `make && sudo make install` following http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_linux building `fifengine` fails due to `error: ‘Point’ is not a member of ‘fcn’`, complete build log provided at https://richtercloud.de:451/index.php/s/V7DUEgQA4Xiqamp.

experienced with `fifechan` 0.1.3-12-gbbb7743 and `fifengine` 0.4.1-126-g7c2fc1b3 on Ubuntu 16.10

**Comment by helios2000** [comment]
It looks like you do use the master version of fifengine instead of 0.4.1.
The 0.4.1 relase of fifengine works with the 0.1.4 release of fifechan. If you want to use master, then you need the master versions of both.

**Comment by helios2000** [comment]
I'll close the issue. If it makes still problem you can reopen it.

**Comment by krichter722** [comment]
> It looks like you do use the master version of fifengine instead of 0.4.1.
The 0.4.1 relase of fifengine works with the 0.1.4 release of fifechan. If you want to use master, then you need the master versions of both.

This is indeed the reason for the issue. I'd be appreciated if a check for the required versions failing with a helpful error message would be added to the `cmake` setup.
