### ISSUE TITLE
Atlas creator tool doesn't compile with Qt 4.8.1 on windows

### ISSUE THREAD

**Issue by otinn** [fifengine/fifengine#740]
The atlas creator tool fails to compile on windows with Qt 4.8.1 with the following error message:

```
atlas\glwidget.cpp:160: error: C3861: 'gluPerspective': identifier not found
```

This can be fixed by including gl/GLU.h in glwidget.cpp
