### ISSUE TITLE
from fife import fife: Cannot import name 'fife'

### ISSUE THREAD

**Issue by shaypal5** [fifengine/fifengine#1064]
Hey there,

First, I want to thank all contributors and maintainers - wow! This looks like an amazing project! :)

Second, I just started playing with it on Ubuntu 16.04. I've built both `fifechan` and `fifengine` from source (after building some requirements from source), both from the latest commits, as I wanted Python 3 supported and as I understand it is not in the latest `fifengine` release yet.

Anyway, so I'm working with Python 3.5.2 installed using pyenv. Used the tutorial to build and install both libraries successfully. Then created a virtualenv on top of Python 3.5.2 and installed the fifengine python package using:
`pip install -e ~/clones/fifengine`

This worked well. Now if I fire up a python (or an Ipython) shell inside this virtualenv I can import fife, and see subpackages such as `extensions`, etc.

However, there's no second `fife` inside the `fife` package installed. And reading the Python part of fifengine, at `engine/python/fife`, I can see why. Reading the `__init__.py` file and generally through this part of the package I don't see any inner `fife` subpackage defined, so I don't know what how this `from fife import fife` code (repeating a few times in the engine itself) is supposed to work.

I'd love your help with understanding what did I get wrong.

Cheers,
Shay

**Comment by Beliaar** [comment]
Well, that fife subpackage is a python extension module (a shared libary linked with python).

It is possible that your install process did not copy that module, and I dont quite remember how the normal install process (in Linux environments) does that.

**Comment by shaypal5** [comment]
Ok. I read a bit about Python extension modules. They should be installed using `python setup.py install`. Maybe `pip install`-ing the folder path does not produce a corresponding process. I'll try it in a couple of days, when I'm back home, and report. Please don't close the issue yet. :)

**Comment by shaypal5** [comment]
Nope. I installed again, with ``python setup.py install`` this time, and I'm getting the same result. What should I do now?

**Comment by LinuxDonald** [comment]
Why you dont install it the normal way? http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_linux

**Comment by shaypal5** [comment]
I did. I followed the instructions to the letter.

**Comment by shaypal5** [comment]
Still, obviously to have the name ``fife`` available in the Python namespace some form of Python package has to be installed...

**Comment by LinuxDonald** [comment]
Maybe its this: https://packages.ubuntu.com/xenial/python3-future

**Comment by shaypal5** [comment]
I meant a Python package as in ``pandas`` or ``requests``, not a packages installation of the Python language; I have a working installation of Python 3.5.

I'm closing the topic as I will not attempt to get ``fifengine`` or the its demos to work; I moved to looking at other game engines to play with. Thank you for your time, guys!
