### ISSUE TITLE
fifengine make error 

### ISSUE THREAD

**Issue by melloskitten** [fifengine/fifengine#1028]
Hello. 

I am following your [manual](http://docs.fifengine.net/developer-manual/en/) to build fifengine and fifechan. I have successfully installed fifechan, but whenever I try to `make && sudo make install` for fifengine, I keep getting the following error: 

`/fifengine/_build/fifePYTHON_wrap.cxx:113588:15: error: no matching       member function for call to 'erase'`

I'm using 

- Linux Mint 17.3 Cinnamon 64-bit, version 2.8.8

- CMake version 3.2.2

- Swig 3.0.12

- Python 2.7.6

- GNU Make 3.81

- gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

and I also built with 

- Ubuntu clang version 3.4-1ubuntu3 

The build was successful with both compilers, but I keep getting the same error.

**Comment by LinuxDonald** [comment]
@helios2000 have you maybe an idea?

**Comment by helios2000** [comment]
Sounds like a C++11 problem or similar with swig. But it should work with the used versions of swig and gcc / clang. I'm sorry, more ideas I have not.

**Comment by melloskitten** [comment]
Alright then - what is the recommended version of swig?

**Comment by helios2000** [comment]
Well, it should works with your 3.0.12, that's the problem. I'm using 3.0.11 but it should not make any difference. I'll try it with 3.0.12 too, maybe they changed something.

**Comment by melloskitten** [comment]
Ah ok. Which clang version do you use ..?

**Comment by melloskitten** [comment]
I just downgraded to swig 3.0.11, still same error

**Comment by helios2000** [comment]
Yea, and I upgraded to 3.0.12 without problems.
I'm on Windows and using MSVC 2015. But our travis do use clang 3.5.0 and gcc 4.8.5.

**Comment by LinuxDonald** [comment]
@melloskitten could you maybe upgrade gcc to version 4.9 from backport repo and test it again?

**Comment by melloskitten** [comment]
Alright, I also tried clang 3.5.0, but alas, no difference.
@LinuxDonald thanks for the suggestion, I will try that asap.

**Comment by LinuxDonald** [comment]
You could also try with clang 3.9

**Comment by Niektory** [comment]
Maybe post the full build log. We might find a hint there.

**Comment by melloskitten** [comment]
**Configs I have at the moment:**
cmake version 3.2.2
clang  version 3.8.0-2ubuntu3~trusty4 (previously  3.4-1)
Rest is same as above.

**fifechan is set up, everything worked.**

**Now to fifengine:**

First I built with only python support.

This is the build log: 

```
sandra@gorbatschow ~/fifengine $ mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.1c5ce75 using build type 'Release'.
--     Source directory is '/home/sandra/fifengine'.
--     Build  directory is '/home/sandra/fifengine/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/sandra/fifengine/../fifengine-dependencies'.

--     CMake version is '3.2.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.0") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.12") 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so  
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found FIFECHAN: /usr/local/lib/libfifechan.so   
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.11") 
-- Found PythonInterp: /usr/bin/python2 (found suitable exact version "2.7.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.6") 
--     Python install directory is '/usr/lib/python2.7/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sandra/fifengine/_build
```

And when I try to make & make install, this is the error -> 

```
make && sudo make install
[  0%] Swig source
Scanning dependencies of target _fife
[  1%] Building CXX object CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx: In function ‘PyObject* _wrap_AnimationOverlayMap_erase__SWIG_2(PyObject*, int, PyObject**)’:
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:113588:30: error: no matching function for call to ‘std::map<int, FIFE::SharedPtr<FIFE::Animation> >::erase(SwigValueWrapper<std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > > >&, SwigValueWrapper<std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > > >&)’
       (arg1)->erase(arg2,arg3);
                              ^
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:113588:30: note: candidates are:
In file included from /usr/include/c++/4.8/map:61:0,
                 from /home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:2954:
/usr/include/c++/4.8/bits/stl_map.h:690:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::iterator std::map<_Key, _Tp, _Compare, _Alloc>::erase(std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator) [with _Key = int; _Tp = FIFE::SharedPtr<FIFE::Animation>; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >]
       erase(const_iterator __position)
       ^
/usr/include/c++/4.8/bits/stl_map.h:690:7: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/stl_map.h:696:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::iterator std::map<_Key, _Tp, _Compare, _Alloc>::erase(std::map<_Key, _Tp, _Compare, _Alloc>::iterator) [with _Key = int; _Tp = FIFE::SharedPtr<FIFE::Animation>; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >]
       erase(iterator __position)
       ^
/usr/include/c++/4.8/bits/stl_map.h:696:7: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/stl_map.h:726:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::size_type std::map<_Key, _Tp, _Compare, _Alloc>::erase(const key_type&) [with _Key = int; _Tp = FIFE::SharedPtr<FIFE::Animation>; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::size_type = long unsigned int; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = int]
       erase(const key_type& __x)
       ^
/usr/include/c++/4.8/bits/stl_map.h:726:7: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/stl_map.h:746:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::iterator std::map<_Key, _Tp, _Compare, _Alloc>::erase(std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator, std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator) [with _Key = int; _Tp = FIFE::SharedPtr<FIFE::Animation>; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >; std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >]
       erase(const_iterator __first, const_iterator __last)
       ^
/usr/include/c++/4.8/bits/stl_map.h:746:7: note:   no known conversion for argument 1 from ‘SwigValueWrapper<std::_Rb_tree_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > > >’ to ‘std::map<int, FIFE::SharedPtr<FIFE::Animation> >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >}’
make[2]: *** [CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/_fife.dir/all] Error 2
make: *** [all] Error 2
```


**Now I'll try to build with Python support with Clang instand of GCC Compiler:** 

```
sandra@gorbatschow ~/fifengine $ mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -D CMAKE_C_COMPILER=clang-3.8 -D CMAKE_CXX_COMPILER=clang++-3.8 ..
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/clang-3.8
-- Check for working C compiler: /usr/bin/clang-3.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-3.8
-- Check for working CXX compiler: /usr/bin/clang++-3.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.1c5ce75 using build type 'Release'.
--     Source directory is '/home/sandra/fifengine'.
--     Build  directory is '/home/sandra/fifengine/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/sandra/fifengine/../fifengine-dependencies'.

--     CMake version is '3.2.2'.
--     CXX Compiler ID: 'Clang'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.0") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.12") 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so  
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found FIFECHAN: /usr/local/lib/libfifechan.so   
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.11") 
-- Found PythonInterp: /usr/bin/python2 (found suitable exact version "2.7.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.6") 
--     Python install directory is '/usr/lib/python2.7/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sandra/fifengine/_build
```

I run make & sudo make install again -> 

```
sandra@gorbatschow ~/fifengine/_build $ make && sudo make install
[  0%] Swig source
Scanning dependencies of target _fife
[  1%] Building CXX object CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:564:7: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
      register size_t l = 0;
      ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:565:7: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
      register size_t r = iter->size - 1;
      ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:568:2: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
        register size_t i = (l + r) >> 1;
        ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:571:4: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
          register int compare = strcmp(name, iname);
          ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:615:7: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
      register size_t i = 0;
      ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:634:3: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
  register const unsigned char *u = (unsigned char *) ptr;
  ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:635:3: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
  register const unsigned char *eu =  u + sz;
  ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:637:5: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
    register unsigned char uu = *u;
    ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:649:3: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
  register unsigned char *u = (unsigned char *) ptr;
  ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:650:3: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
  register const unsigned char *eu = u + sz;
  ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:652:5: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
    register char d = *(c++);
    ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:653:5: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
    register unsigned char uu;
    ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:1330:7: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
      register int i;
      ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:1340:5: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
    register Py_ssize_t l = PyTuple_GET_SIZE(args);
    ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:1350:7: warning: 'register' storage class
      specifier is deprecated and incompatible with C++1z [-Wdeprecated-register]
      register int i;
      ^~~~~~~~~
/home/sandra/fifengine/_build/fifePYTHON_wrap.cxx:113588:15: **error: no matching member
      function for call to 'erase'**
      (arg1)->erase(arg2,arg3);
      ~~~~~~~~^~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_map.h:746:7: note: 
      candidate function not viable: no known conversion from 'SwigValueWrapper<std::map<int,
      FIFE::SharedPtr<FIFE::Animation> >::iterator>' (aka
      'SwigValueWrapper<_Rb_tree_iterator<std::pair<const int,
      FIFE::SharedPtr<FIFE::Animation> > > >') to 'const_iterator' (aka
      '_Rb_tree_const_iterator<std::pair<const int, FIFE::SharedPtr<FIFE::Animation> > >')
      for 1st argument
      erase(const_iterator __first, const_iterator __last)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_map.h:690:7: note: 
      candidate function not viable: requires single argument '__position', but 2 arguments
      were provided
      erase(const_iterator __position)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_map.h:696:7: note: 
      candidate function not viable: requires single argument '__position', but 2 arguments
      were provided
      erase(iterator __position)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_map.h:726:7: note: 
      candidate function not viable: requires single argument '__x', but 2 arguments were
      provided
      erase(const key_type& __x)
      ^
15 warnings and 1 error generated.
make[2]: *** [CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/_fife.dir/all] Error 2
make: *** [all] Error 2

```

_Sobs I just wanted to contribute a bit to unknown-horizons but this is really upsetting haha_

**Comment by LinuxDonald** [comment]
Clang 3.9 backports: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main
You need:
- clang-3.9
- llvm-3.9-dev
- libclang-3.9-dev
Swig 3:
deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list'; sudo apt-get update -qq; sudo apt-get install -yqq swig3.0/trusty-backports

You can too upgrade gcc to 4.9

**Comment by melloskitten** [comment]
THANK YOU! It finally worked.  Thanks for your help, I really really appreciate it! :) 

Maybe you can also link to this issue in your FAQ section for other people? In case they run into the same problems? :)
